header:
  Dashboard: "admin_dashboard_path"
  Configurações: ""
  Profile: ""
  Site: "root_path"

lateral:
  Administradores: "admin_admins_path"
  Produtos: "admin_products_path"
  Addons: "admin_addons_path"